# fly.toml file generated for dont-get-got on 2022-01-06T15:09:32-06:00

app = "dont-get-got"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  cmd = "./dont-get-got-online"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    port = "8000"
    restart_limit = 6
    timeout = "2s"
